name: "Get changes"
description: "Get changed files in commits"
outputs:
  changes:
    description: "Commit changes"
    value: ${{ steps.process-changes.outputs.changes }}
runs:
  using: "composite"
  steps:
    - name: Get problems
      id: all-problems
      uses: TNFSH-Programming-Contest/tps-actions/.github/actions/get-problems@main

    - uses: dorny/paths-filter@v2
      id: changes
      with:
        list-files: 'json'
        filters: |
          input:
            - '*/gen/**'
          solutions:
            - '*/solution/**'
            - '*/solutions.json'
          pdf:
            - '*/scripts/statement.sh'
            - '*/statement/*.jpg'
            - '*/statement/DISABLE_AUTO_BUILD'
            - '*/statement/index.md'
          template:
            - 'template.tex'
          cover:
            - 'cover.tex'
          verify:
            - 'p*/**'

    - name: Check changes in config
      if: github.event_name == 'push'
      shell: bash
      run: |
        set +e

        FLAGPATH=$RUNNER_TEMP/flags
        mkdir -p $FLAGPATH

        PROBLEMS="${{ steps.all-problems.outputs.problems }}"

        for pro in $PROBLEMS; do
          echo "Check $pro"

          git diff ${{ github.event.before }}..HEAD -U0 p${pro}/problem.json | grep '"time_limit"'
          if [ $? -eq 0 ]; then
            echo "$pro" > $FLAGPATH/solutions-${pro}
          else
            echo "No changes in problem.json for solutions";
          fi

          git diff ${{ github.event.before }}..HEAD -U0 p${pro}/solutions.json | grep '"model_solution"'
          if [ $? -eq 0 ]; then
            echo "$pro" > $FLAGPATH/input-${pro}
          else
            echo "No changes in solutions.json for input";
          fi

          git diff ${{ github.event.before }}..HEAD -U0 p${pro}/subtasks.json | grep '"score"'
          if [ $? -eq 0 ]; then
            echo "$pro" > $FLAGPATH/solutions-${pro}
          else
            echo "No changes in subtasks.json for solutions";
          fi

          git diff ${{ github.event.before }}..HEAD -U0 p${pro}/problem.json | grep '"contest_name"\|"problem_label"\|"name"\|"title"\|"memory_limit"\|"time_limit"'
          if [ $? -eq 0 ]; then
            echo "$pro" > $FLAGPATH/pdf-${pro}
          else
            echo "No changes in problem.json for pdf";
          fi

          git diff ${{ github.event.before }}..HEAD -U0 p${pro}/subtasks.json | grep '"index"\|"score"\|"text"'
          if [ $? -eq 0 ]; then
            echo "$pro" > $FLAGPATH/pdf-${pro}
          else
            echo "No changes in subtasks.json for pdf";
          fi
        done

    - name: Process
      id: process-changes
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        CHANGES: ${{ toJSON(steps.changes.outputs) }}
        PROBLEMS: ${{ steps.all-problems.outputs.problemsjson }}
        FLAGPATH: ${{ runner.temp }}/flags
      run: |
        python3 parse.py
